#!/usr/bin/env bash
# ================================================================
#  Sentiment-Aware EHR Predictive Engine
#  One-Click Setup & Start — Linux / macOS
#
#  Run this once after unzipping the project:
#    chmod +x setup.sh && ./setup.sh
#
#  It will:
#    1. Verify Python 3.10+ and Bun/Node.js are installed
#    2. Create a Python virtual environment
#    3. Install all backend dependencies
#    4. Download the spaCy language model
#    5. Create a ready-to-use .env  (SQLite — no database setup needed)
#    6. Install all frontend dependencies
#    7. Start backend (port 8000) and frontend (port 8080) side-by-side
# ================================================================
set -e

PROJECT_ROOT="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
BLUE='\033[1;34m'; GREEN='\033[0;32m'; YELLOW='\033[1;33m'; RED='\033[0;31m'; NC='\033[0m'

info()    { echo -e "${BLUE}[INFO]${NC}  $*"; }
success() { echo -e "${GREEN}[OK]${NC}    $*"; }
warn()    { echo -e "${YELLOW}[WARN]${NC}  $*"; }
die()     { echo -e "${RED}[ERROR]${NC} $*" >&2; exit 1; }

echo ""
echo "================================================================"
echo " Sentiment-Aware EHR Predictive Engine — One-Click Setup"
echo "================================================================"
echo ""

# ── Check Python ─────────────────────────────────────────────────
info "Looking for Python 3.10+..."
PYTHON=""
for cmd in python3.12 python3.11 python3.10 python3 python; do
    if command -v "$cmd" &>/dev/null; then
        ver=$("$cmd" -c "import sys; print(f'{sys.version_info.major}.{sys.version_info.minor}')" 2>/dev/null)
        major=${ver%%.*}; minor=${ver##*.}
        if [[ "$major" -ge 3 && "$minor" -ge 10 ]]; then
            PYTHON="$cmd"
            success "Found $cmd ($ver)"
            break
        fi
    fi
done
[[ -z "$PYTHON" ]] && die "Python 3.10+ not found.\nInstall it from: https://www.python.org/downloads/"

# ── Check Node package manager ───────────────────────────────────
info "Looking for Bun or Node.js..."
PKG_MGR=""
if command -v bun &>/dev/null; then
    PKG_MGR="bun"
    success "Found Bun $(bun --version)"
elif command -v node &>/dev/null; then
    PKG_MGR="npm"
    success "Found Node.js $(node --version) (npm fallback)"
else
    die "Neither Bun nor Node.js found.\nInstall Bun : https://bun.sh\nInstall Node: https://nodejs.org"
fi

echo ""

# ── Step 1: Python venv ───────────────────────────────────────────
info "[1/6] Setting up Python virtual environment..."
if [[ -f "$PROJECT_ROOT/venv/bin/activate" ]]; then
    info "      venv already exists — skipping creation."
else
    "$PYTHON" -m venv "$PROJECT_ROOT/venv"
    success "      Created venv."
fi
# shellcheck disable=SC1091
source "$PROJECT_ROOT/venv/bin/activate"

# ── Step 2: Backend dependencies ─────────────────────────────────
info "[2/6] Installing backend dependencies (this may take a few minutes)..."
pip install --upgrade pip --quiet
pip install -r "$PROJECT_ROOT/requirements.txt" --quiet
success "      Backend dependencies installed."

# ── Step 3: spaCy model ───────────────────────────────────────────
info "[3/6] Downloading spaCy language model (en_core_web_sm)..."
if python -c "import spacy; spacy.load('en_core_web_sm')" &>/dev/null; then
    info "      spaCy model already present — skipping."
else
    python -m spacy download en_core_web_sm --quiet && success "      spaCy model downloaded." \
        || warn "spaCy model download failed. Run later: source venv/bin/activate && python -m spacy download en_core_web_sm"
fi

# ── Step 4: .env ─────────────────────────────────────────────────
info "[4/6] Configuring environment..."
if [[ -f "$PROJECT_ROOT/.env" ]]; then
    info "      .env already exists — skipping."
else
    cat > "$PROJECT_ROOT/.env" <<'EOF'
# Auto-generated by setup.sh
# SQLite is used by default — no external database required.
# For production, switch to PostgreSQL and change JWT_SECRET.

DATABASE_URL=sqlite+aiosqlite:///./ehr_db.sqlite3
CLINICALBERT_MODEL=medicalai/ClinicalBERT
ARTIFACTS_DIR=artifacts
LOG_DIR=logs
LOG_LEVEL=INFO
MAX_TOKEN_LENGTH=512
DISTRESS_CLASS_WEIGHT=3.0
ATTENTION_TOP_K=10
JWT_SECRET=dev-only-secret-replace-before-deploying
JWT_EXPIRY_MINUTES=30
REFRESH_TOKEN_EXPIRY_DAYS=7
EOF
    success "      Created .env with SQLite defaults."
fi

# ── Step 5: Frontend dependencies ────────────────────────────────
info "[5/6] Installing frontend dependencies..."
cd "$PROJECT_ROOT/frontend"
if [[ "$PKG_MGR" == "bun" ]]; then
    bun install --silent
else
    npm install --silent
fi
success "      Frontend dependencies installed."
cd "$PROJECT_ROOT"

# ── Summary ──────────────────────────────────────────────────────
echo ""
echo "================================================================"
echo ""
echo " IMPORTANT — First startup note:"
echo " The backend will download ClinicalBERT (~400 MB) from"
echo " HuggingFace on first launch. This is a one-time download."
echo " Subsequent starts are instant."
echo ""
echo " Default accounts (all use password: Password123!):"
echo "   admin1    — Administrator"
echo "   doctor1   — Clinician"
echo "   nurse1    — Clinician"
echo "   analyst1  — Analyst"
echo "   patient1  — Patient"
echo "   patient2  — Patient"
echo ""
echo " Once both servers are running, open your browser at:"
echo "   http://localhost:8080"
echo ""
echo " Backend API docs: http://localhost:8000/docs"
echo ""
echo "================================================================"
echo ""
info "[6/6] Starting servers..."
echo ""

# ── Trap — kill both servers on Ctrl-C ───────────────────────────
BACKEND_PID=""
FRONTEND_PID=""
cleanup() {
    echo ""
    info "Shutting down servers..."
    [[ -n "$BACKEND_PID" ]]  && kill "$BACKEND_PID"  2>/dev/null
    [[ -n "$FRONTEND_PID" ]] && kill "$FRONTEND_PID" 2>/dev/null
    wait 2>/dev/null
    echo " Servers stopped. Goodbye."
    exit 0
}
trap cleanup INT TERM

# ── Launch backend ────────────────────────────────────────────────
source "$PROJECT_ROOT/venv/bin/activate"
uvicorn app.main:app --host 0.0.0.0 --port 8000 --reload &
BACKEND_PID=$!
success "Backend  started (PID $BACKEND_PID) → http://localhost:8000"

# ── Launch frontend ───────────────────────────────────────────────
cd "$PROJECT_ROOT/frontend"
if [[ "$PKG_MGR" == "bun" ]]; then
    bun dev &
else
    npm run dev &
fi
FRONTEND_PID=$!
success "Frontend started (PID $FRONTEND_PID) → http://localhost:8080"
cd "$PROJECT_ROOT"

echo ""
echo " Both servers are running. Press Ctrl+C to stop everything."
echo ""

# ── Wait ──────────────────────────────────────────────────────────
wait
