@echo off
setlocal EnableDelayedExpansion

REM ================================================================
REM  Sentiment-Aware EHR Predictive Engine
REM  One-Click Setup ^& Start — Windows
REM
REM  Run this once after unzipping the project.
REM  It will:
REM    1. Verify Python 3.10+ and Bun/Node.js are installed
REM    2. Create a Python virtual environment
REM    3. Install all backend dependencies
REM    4. Download the spaCy language model
REM    5. Create a ready-to-use .env (SQLite — no database setup needed)
REM    6. Install all frontend dependencies
REM    7. Open two terminal windows: backend (port 8000) + frontend (port 8080)
REM ================================================================

echo.
echo  ================================================================
echo   Sentiment-Aware EHR Predictive Engine — One-Click Setup
echo  ================================================================
echo.

REM ── Store project root ───────────────────────────────────────────
SET "PROJECT_ROOT=%~dp0"
REM Strip trailing backslash
IF "%PROJECT_ROOT:~-1%"=="\" SET "PROJECT_ROOT=%PROJECT_ROOT:~0,-1%"

REM ── Check Python ─────────────────────────────────────────────────
echo [CHECK] Looking for Python 3.10+...
python --version >nul 2>&1
IF ERRORLEVEL 1 (
    echo.
    echo  [ERROR] Python was not found in PATH.
    echo  Install Python 3.10+ from: https://www.python.org/downloads/
    echo  Make sure to tick "Add Python to PATH" during install.
    echo.
    pause
    exit /b 1
)
FOR /F "tokens=2" %%V IN ('python --version 2^>^&1') DO SET PY_VER=%%V
echo         Found Python %PY_VER%

REM ── Check Node package manager (Bun preferred, npm fallback) ─────
SET "PKG_MGR=npm"
SET "PKG_RUN=npm run"
bun --version >nul 2>&1
IF NOT ERRORLEVEL 1 (
    SET "PKG_MGR=bun"
    SET "PKG_RUN=bun run"
    FOR /F %%V IN ('bun --version 2^>^&1') DO echo [CHECK] Found Bun %%V
    GOTO :check_done
)
node --version >nul 2>&1
IF NOT ERRORLEVEL 1 (
    FOR /F %%V IN ('node --version 2^>^&1') DO echo [CHECK] Found Node.js %%V ^(npm fallback^)
    GOTO :check_done
)
echo.
echo  [ERROR] Neither Bun nor Node.js was found.
echo  Install Bun  : https://bun.sh
echo  Install Node : https://nodejs.org  (LTS recommended)
echo.
pause
exit /b 1
:check_done

echo.

REM ── Step 1: Python virtual environment ───────────────────────────
echo [1/6] Setting up Python virtual environment...
IF EXIST "%PROJECT_ROOT%\venv\Scripts\activate.bat" (
    echo       venv already exists — skipping creation.
) ELSE (
    python -m venv "%PROJECT_ROOT%\venv"
    IF ERRORLEVEL 1 (
        echo  [ERROR] Failed to create virtual environment.
        pause
        exit /b 1
    )
    echo       Created venv.
)

REM ── Step 2: Backend dependencies ─────────────────────────────────
echo [2/6] Installing backend dependencies (this may take a few minutes)...
CALL "%PROJECT_ROOT%\venv\Scripts\activate.bat"
python -m pip install --upgrade pip --quiet
pip install -r "%PROJECT_ROOT%\requirements.txt" --quiet
IF ERRORLEVEL 1 (
    echo.
    echo  [ERROR] pip install failed. Check your internet connection and try again.
    pause
    exit /b 1
)
echo       Backend dependencies installed.

REM ── Step 3: spaCy language model ─────────────────────────────────
echo [3/6] Downloading spaCy language model (en_core_web_sm)...
python -c "import spacy; spacy.load('en_core_web_sm')" >nul 2>&1
IF NOT ERRORLEVEL 1 (
    echo       spaCy model already present — skipping.
) ELSE (
    python -m spacy download en_core_web_sm --quiet
    IF ERRORLEVEL 1 (
        echo  [WARNING] spaCy model download failed. Text preprocessing will be limited.
        echo            Run manually later:  venv\Scripts\activate ^&^& python -m spacy download en_core_web_sm
    ) ELSE (
        echo       spaCy model downloaded.
    )
)

REM ── Step 4: Create .env ───────────────────────────────────────────
echo [4/6] Configuring environment...
IF EXIST "%PROJECT_ROOT%\.env" (
    echo       .env already exists — skipping.
) ELSE (
    (
        echo # Auto-generated by setup.bat
        echo # SQLite is used by default — no external database required.
        echo # For production, switch to PostgreSQL and change JWT_SECRET.
        echo.
        echo DATABASE_URL=sqlite+aiosqlite:///./ehr_db.sqlite3
        echo CLINICALBERT_MODEL=medicalai/ClinicalBERT
        echo ARTIFACTS_DIR=artifacts
        echo LOG_DIR=logs
        echo LOG_LEVEL=INFO
        echo MAX_TOKEN_LENGTH=512
        echo DISTRESS_CLASS_WEIGHT=3.0
        echo ATTENTION_TOP_K=10
        echo JWT_SECRET=dev-only-secret-replace-before-deploying
        echo JWT_EXPIRY_MINUTES=30
        echo REFRESH_TOKEN_EXPIRY_DAYS=7
    ) > "%PROJECT_ROOT%\.env"
    echo       Created .env with SQLite defaults.
)

REM ── Step 5: Frontend dependencies ────────────────────────────────
echo [5/6] Installing frontend dependencies...
cd /d "%PROJECT_ROOT%\frontend"
IF "%PKG_MGR%"=="bun" (
    bun install --silent
) ELSE (
    npm install --silent
)
IF ERRORLEVEL 1 (
    echo.
    echo  [ERROR] Frontend dependency install failed.
    pause
    exit /b 1
)
echo       Frontend dependencies installed.
cd /d "%PROJECT_ROOT%"

REM ── Step 6: Done — show summary ──────────────────────────────────
echo [6/6] Setup complete!
echo.
echo  ================================================================
echo.
echo   IMPORTANT — First startup note:
echo   The backend will download ClinicalBERT (~400 MB) from
echo   HuggingFace on first launch. This is a one-time download.
echo   Subsequent starts are instant.
echo.
echo   Default accounts (all use password: Password123!):
echo     admin1    — Administrator
echo     doctor1   — Clinician
echo     nurse1    — Clinician
echo     analyst1  — Analyst
echo     patient1  — Patient
echo     patient2  — Patient
echo.
echo   Once both servers are running, open your browser at:
echo     http://localhost:8080
echo.
echo   Backend API docs: http://localhost:8000/docs
echo.
echo  ================================================================
echo.
echo  Two new windows will open now:
echo    - "EHR Backend"  (FastAPI on port 8000)
echo    - "EHR Frontend" (Vite on port 8080)
echo.
echo  Press any key to launch...
pause >nul

REM ── Launch backend ────────────────────────────────────────────────
start "EHR Backend" cmd /k "cd /d "%PROJECT_ROOT%" && call venv\Scripts\activate && uvicorn app.main:app --host 0.0.0.0 --port 8000 --reload && pause"

REM ── Launch frontend ───────────────────────────────────────────────
IF "%PKG_MGR%"=="bun" (
    start "EHR Frontend" cmd /k "cd /d "%PROJECT_ROOT%\frontend" && bun dev && pause"
) ELSE (
    start "EHR Frontend" cmd /k "cd /d "%PROJECT_ROOT%\frontend" && npm run dev && pause"
)

echo.
echo  Servers are starting. Watch the two new windows for progress.
echo  Close this window at any time.
echo.
pause
endlocal
